### ISSUE TITLE
Decouple from ColdBox

### ISSUE THREAD

**Issue by adamcameron** [ryanalbrecht/cfml-ip#1]
Given this is a fairly generic library, it would be really nice if the core lib didn't have ColdBox dependencies baked into it, and instead the lib code was stand-alone (and usable that way), and the ColdBox bits were in a separate ColdBoxSdk / ColdBoxConnector or something like that.

Also not sure a project written in CFML really needs "cfml" in its name ;-)

As it stands it looks to me like this is unusable outside the context of ColdBox :-(

That's not to take anything away from your fine efforts one bit. I think it's just painted itself into a corner a bit.

Cheers anyhow!

**Comment by ryanalbrecht** [comment]
Hi @adamcameron 

This is a tricky issue as I utilize the cbjavaloader module which itself, also has the same coldbox dependencies. If I get time I will look at removing the 'coldboxyness' of the module. This module was intended to be coldbox module so at least for the near future I will leave it as is and leave this issue open until I get around to it.

Regards
Ryan

**Comment by ryanalbrecht** [comment]
@adamcameron I have rewritten this modules to be a self contained cfc using vanilla CFML.

I have only ever lived in Coldbox land when working with modules and wirebox. I am interested in what exactly you had in mind when you needed the coldbox dependencies removed. 

I assume I basically just need a box.cfc and the new ip.cfc class in a single folder and that should be usable in all types of applications right?

**Comment by ryanalbrecht** [comment]
Closed. 

I will be supporting https://github.com/ryanalbrecht/ip going forward

**Comment by adamcameron** [comment]
Hi Ryan. Sorry to take a while to get back to you. GMail conveniently filed this in a category I don't pay attn to, and it skipped my inbox.

Looking at the current codebase, these bits are all assuming one is using ColdBox / WireBox:

```
/ModuleConfig.cfc
wireBox.getInstance( "loader@cbjavaloader" ).appendPaths( settings.libPath );

/models/IP.cfc
component singleton
property name="javaLoader" inject="loader@cbjavaloader";
```

If an object is supposed to be a singleton, this should be done via a (ideally) static factory method, not by having *Box-specific annotations which are meaningless outside of *Box.

And it's fine to require a Java loader, but should not rely on WireBox magic to have it injected. It should either be a constructor arg, or have a setter. Then any DI container mechanism, or hand-cranking will work. Given it's so intrinsic to the operations of the lib, probably a constructor arg rather than a setter. Or in this case an arg passed to the static factory method, as the `init` function should just throw an exception as part of ensuring the object is a singleton. That said, does it *need* to be a singleton? I can't see why it would?
